services:
  - type: web
    name: gestor-incidencias
    env: java
    region: oregon
    plan: free
    buildCommand: "mvn clean package -DskipTests"
    startCommand: "java -jar target/GESTOR-DE-INCIDENCIAS-LA-CASA-DEL-ALFAJOR-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DB_URL
        value: jdbc:mysql://bekr3fcvhyzcxxeviuvh-mysql.services.clever-cloud.com:3306/bekr3fcvhyzcxxeviuvh?useSSL=false&serverTimezone=UTC
      - key: DB_USER
        value: um44d2pme4onzsxx
      - key: DB_PASS
        sync: false
